import subprocess
import logging

def create_auto_healing_pr(branch_name, message):
    try:
        subprocess.run(["git", "checkout", "-b", branch_name], check=True)
        subprocess.run(["git", "add", "main.tf.json"], check=True)
        subprocess.run(["git", "commit", "-m", message], check=True)
        subprocess.run(["git", "push", "origin", branch_name], check=True)
        # Nota: gh pr create requiere autenticación previa
        subprocess.run(["gh", "pr", "create", "--title", message, "--body", "Auto-healing PR generated by SRE-Gen"], check=True)
        return True
    except Exception as e:
        logging.error(f"Failed to create PR: {e}")
        return False
